{'application': True,
 'assets': {'web.assets_backend': ['ai_business_assistant_anydb_v116/static/description/icon.png',
                                   'ai_business_assistant_anydb_v116/static/src/js/ai_assistant_client.js']},
 'author': 'You + ChatGPT',
 'category': 'Productivity',
 'data': ['security/ir.model.access.csv',
          'data/set_groq_defaults.xml',
          'data/set_groq_key.xml',
          'data/ai_client_action.xml'],
 'depends': ['account',
             'base',
             'base_setup',
             'purchase',
             'sale',
             'sale_management',
             'stock',
             'web',
             'website'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'AI Business Assistant v118 (Agentic Multi‑Turn + Name Guard)',
 'summary': 'Ask anything about your Odoo data; safe generic tools + Groq defaults '
            '(OpenAI-compatible).',
 'version': '17.0.118.1+voice2',
 'website': 'https://example.com'}